config/routes.rb
Rails.application.routes.draw do
  resources :exams

  get '/edit_question/:id' , to: 'admin/questions#edit_question', as: :edit_question

  get 'sessions/new'

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  namespace :admin do
    resources :questions
  end

  resources :users do
    member do
      get :confirm_email
    end
  end

  post '/result', to: 'admin/questions#result'
  resources :results
  get '/show', to: 'results#show'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	before_save { email.downcase! }
	validates :name, presence: true
	validates :email, presence: true,uniqueness: true
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }
	validates :password_confirmation, presence: true
	has_many :results
	has_many :questions, :through => :results

  before_create :confirmation_token

  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!(:validate => false)
  end

  private

  def confirmation_token
    if self.confirm_token.blank?
      self.confirm_token = SecureRandom.urlsafe_base64.to_s
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user,only: [:edit, :update, :destroy]
  before_action :correct_user,  only: [:edit, :update]
  before_action :admin_user, only: :destroy
  def new
    redirect_to root_url if current_user
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      UserMailer.registration_confirmation(@user).deliver
      flash[:success] = "Please confirm your email address to continue"
      redirect_to root_url
  	else
      flash[:error] = "Ooooppss, something went wrong!"
  		render 'new'
  	end
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end


  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success]="Profile Updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success]="User deleted"
    redirect_to users_url
  end

  def confirm_email
    user = User.find_by_confirm_token(params[:id])
    if user
      user.email_activate
      flash[:success] = "Welcome to the Sample App! Your email has been confirmed.
      Please sign in to continue."
      redirect_to login_url
    else
      flash[:error] = "Sorry. User does not exist"
      redirect_to root_url
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger]="Please log in."
      redirect_to login_url
    end
  end

  def correct_user
    @user=User.find(params[:id])
    redirect_to (root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to (root_url) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class='form_heading dashboard_form''>
  <h1>Settings</h1>
  <div class="frm_setting_col">
    <div class="col-md-4 col-md-offset-4">
      <%= form_for(@user, url: user_path, method: 'put', html: { class: '' }) do |f| %>
        <% if @user.errors.any? %>
          <div id='error_explanation'>
            <ul>
              <% @user.errors.each do |attri, msg| %>
                <li>
                  <%= attri %> <%= msg %>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class='form-group'>
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class='form-group'>
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>

        <div class='form-group'>
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>

        <div class='form-group'>
          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>

        </div>

        <div class='actions'>
          <%#= f.submit 'Update', class: 'btn btn-md btn-primary default_btn' %>
          <button name="button" type="submit">Update</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title,'All Users') %>
<h1>All Users</h1>

<ul class="users">
  <% @users.each do |user| %>
  	<li>
  	  <%= link_to user.name,user %>
  	  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
      <% end %>

  	</li>
  <% end %>
</ul> 

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title,@user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
       </h1>
    </section>
  </aside>
</div>       