config/routes.rb
Rails.application.routes.draw do
  resources :exams

  get '/edit_question/:id' , to: 'admin/questions#edit_question', as: :edit_question

  get 'sessions/new'

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  namespace :admin do
    resources :questions
  end

  resources :users do
    member do
      get :confirm_email
    end
  end

  post '/result', to: 'admin/questions#result'
  resources :results
  get '/show', to: 'results#show'
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :exam
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  before_action :admin_user, only: [:new, :edit]
  def new
	  @question = Question.new
  end
    
  def index 
    #binding.pry
    @exams = Exam.all
  end

  def edit
  	#binding.pry
	  @question = Question.find(params[:id])
  end

  def edit_question
	  @question = Question.find(params[:id])
  end
  
  def create
  	#binding.pry
    @question = Question.new(question_params)
    if @question.save
      redirect_to exams_path
    else
      render 'new'
    end
  end

  def update
  	#binding.pry
    @question = Question.find(params[:id])
    if @question.update(params[:question].permit(:question, :option1, :option2, :option3, :option4, :answer, :exam_id))
    flash[:success] = "Question Updated"  
      redirect_to @question.exam
    else 
      render 'edit'
    end
  end
 
 
  def show
  	#binding.pry
    #@exam_questions = Question.all
    @exam_questions = Question.where("exam_id = ?", params[:id])
    @exam_id = params[:id]
  end

  def result
    mark = 0
    #binding.pry
    params[:question].each do |key, value|
         #binding.pry
      if(key == "exam_id")
         @exam_id = value
      else
         k = key.to_i
         @question = Question.find(k)
          if(@question.answer == value)
            mark += 1
          end
      end
    end

    #exam_id = params[:question][:exam_id]
    @result = Result.create(mark: mark, user_id: current_user.id, exam_id: @exam_id )
    if @result.save
      redirect_to root_path
    else
      redirect_to admin_questions_path
    end 
  end 

  private
  
  def question_params
    params.require(:question).permit(:question, :option1, :option2,
                                   :option3, :option4, :answer, :exam_id)
  end
  
  def admin_user
    redirect_to (root_url) unless current_user.admin?
  end
end

app/views/admin/questions/edit.html.erb
<% provide(:title, 'Add question') %>
<h1>Add question</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@question,url: admin_question_path(@question)) do |f| %>

    <%= f.label :Question %>
    <%= f.text_field :question, class: 'form-control' %><br>

    <%= f.label :option1 %>
    <%= f.text_field :option1, class: 'form-control' %><br>

    <%= f.label :option2 %>
    <%= f.text_field :option2, class: 'form-control' %><br>


    <%= f.label :Option3 %>
    <%= f.text_field :option3, class: 'form-control' %><br>

    <%= f.label :Option4 %>
    <%= f.text_field :option4, class: 'form-control' %><br>

    <%= f.label :Answer %>
    <%= f.text_field :answer, class: 'form-control' %><br>

    
    <%= f.submit "Add Question", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<%= link_to 'Show', @exam %> |
<%= link_to 'Back', exams_path %>

app/views/admin/questions/edit_question.html.erb
<% provide(:title, 'Edit question') %>
<h1>Edit question</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@question, url: admin_question_path(@question)) do |f| %>

    <%= f.label :Question %>
    <%= f.text_field :question, :value => @question.question, class: 'form-control' %><br>

    <%= f.label :option1 %>
    <%= f.text_field :option1, :value => @question.option1, class: 'form-control' %><br>

    <%= f.label :option2 %>
    <%= f.text_field :option2, :value => @question.option2, class: 'form-control' %><br>

    <%= f.label :Option3 %>
    <%= f.text_field :option3, :value => @question.option3, class: 'form-control' %><br>

    <%= f.label :Option4 %>
    <%= f.text_field :option4, :value => @question.option4, class: 'form-control' %><br>

    <%= f.label :Answer %>
    <%= f.text_field :answer, :value => @question.answer, class: 'form-control' %><br>

    <%#= f.hidden_field :exam_id, :value => params[:id] %>

    <%= f.submit "Update Question", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<%= link_to 'Show', @exam %> |
<%= link_to 'Back', exams_path %>

app/views/admin/questions/index.html.erb
 <h1>List of Exams:</h1>
</br>
<%@exams.each do |exam|%>
<%= link_to exam.title, admin_question_path(exam.id)%></br>

<div><%= link_to "Start Exam", admin_question_path(exam.id), class: "btn btn-sm btn-primary" %></div></br>
<%end%> 

app/views/admin/questions/new.html.erb
 <%= link_to "Create Exam", exams_path %>

app/views/admin/questions/show.html.erb
<strong>List of Question </strong><br>

<%= form_for(:question, url: result_path) do |f| %>
  <% qNo = 0 %>
  
  <%= f.hidden_field :exam_id, :value => params[:id] %>
  
 
  <% @exam_questions.each do |x| %>
    <%= qNo += 1 %>
    <%= x.question %>   
             
    <p>
      A).<%= f.radio_button x.id, 'A'%> 
      <%= x.option1 %>
    </p>
    <p>
      B).<%= f.radio_button x.id, 'B' %>
      <%= x.option2 %>
    </p>
    <p>
      C).<%= f.radio_button x.id, 'C' %>
      <%= x.option3 %>
    </p>
    <p>
      D).<%= f.radio_button x.id, 'D' %>
      <%= x.option4 %>
    </p>
  <% end %>
  <%= f.submit 'Submit' %>
<% end %>