config/routes.rb
Rails.application.routes.draw do
  resources :exams

  get '/edit_question/:id' , to: 'admin/questions#edit_question', as: :edit_question

  get 'sessions/new'

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  namespace :admin do
    resources :questions
  end

  resources :users do
    member do
      get :confirm_email
    end
  end

  post '/result', to: 'admin/questions#result'
  resources :results
  get '/show', to: 'results#show'
end

app/models/exam.rb
class Exam < ApplicationRecord
	has_many :questions, dependent: :destroy
	has_many :results, dependent: :destroy
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
	before_action :set_exam, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: [:new, :index, :edit, :show]
  def new
  	@exam = Exam.new
  end

  def index
  	@exams = Exam.all
  end

  def create
  	@exam = Exam.new(exam_params)
    if @exam.save
      redirect_to exams_path
    else
      render 'new'
    end
  end

  def edit
  	#binding.pry
  	@exam = Exam.find(params[:id])
  end

  def show
	#@exams = Exam.all
  #binding.pry
	  @exam_questions = Question.where("exam_id = ?", params[:id])
    @exam_id = params[:exam]
    @user_id = params[:id]
  end

  def update
    @exam = Exam.find(params[:id])
    if @exam.update(params[:exam].permit(:title))
      redirect_to @exam
    else 
      render 'edit'
    end
  end

  def destroy
 	  @exam = Exam.find(params[:id])
    @exam.destroy
    redirect_to exams_path
  end

  private

  def set_exam
    @exam = Exam.find(params[:id])
  end

  def exam_params
    params.require(:exam).permit(:title)
  end

  def admin_user
    redirect_to (root_url) unless current_user.admin?
  end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_form.html.erb
<%= form_for(@exam) do |f| %>
  <% if @exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
      <% @exam.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exams/edit.html.erb
<% provide(:title, 'Add question') %>
<h1>Add question</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:question,url: admin_questions_path) do |f| %>

    <%= f.label :Question %>
    <%= f.text_field :question, class: 'form-control' %><br>

    <%= f.label :option1 %>
    <%= f.text_field :option1, class: 'form-control' %><br>

    <%= f.label :option2 %>
    <%= f.text_field :option2, class: 'form-control' %><br>


    <%= f.label :Option3 %>
    <%= f.text_field :option3, class: 'form-control' %><br>

    <%= f.label :Option4 %>
    <%= f.text_field :option4, class: 'form-control' %><br>

    <%= f.label :Answer %>
    <%= f.text_field :answer, class: 'form-control' %><br>

    <%= f.hidden_field :exam_id, :value => params[:id] %>

    <%= f.submit "Add Question", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<%= link_to 'Show', @exam %> |
<%= link_to 'Back', exams_path %>

app/views/exams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Exams</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exams.each do |exam| %>
      <tr>
        <td><%=  exam.title %></td>       
        <td><%= link_to 'Show', exam %></td>
        <td><%= link_to 'Add', edit_exam_path(exam) %></td>
        <td><%= link_to 'Destroy', exam, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
        <td><%= link_to 'Result', show_path(exam) %></td>     
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exam', new_exam_path %>

app/views/exams/new.html.erb
New Exam
<%= render 'form' %> <%= link_to 'Back', exams_path %> 

app/views/exams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>

  <%= @exam.title %>
</p>

<strong>List of Question </strong><br>
<%= form_for (:question) do |f| %>
  <% qNo = 0 %>

  <% @exam_questions.each do |x| %>


   <%= qNo += 1 %>
   <%= x.question %>

   <p>
     A).<%= f.radio_button x.id,'A'%>
     <%= x.option1 %>
   </p>
   <p>
     B).<%= f.radio_button x.id, 'B' %>
     <%= x.option2 %>
   </p>
   <p>
     C).<%= f.radio_button x.id, 'C' %>
     <%= x.option3 %>
   </p>
   <p>
     D).<%= f.radio_button x.id, 'D' %>
     <%= x.option4 %>
   </p>
   <%= link_to 'Edit', edit_question_path(x.id) %> </br>
  <% end %>
<% end %>



<%= link_to 'Add Questions', edit_exam_path(@exam) %> |
<%= link_to 'Back', exams_path %>