config/routes.rb
Rails.application.routes.draw do
  resources :exams

  get '/edit_question/:id' , to: 'admin/questions#edit_question', as: :edit_question

  get 'sessions/new'

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  namespace :admin do
    resources :questions
  end

  resources :users do
    member do
      get :confirm_email
    end
  end

  post '/result', to: 'admin/questions#result'
  resources :results
  get '/show', to: 'results#show'
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "online exam system", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",root_path %></li>

            <% if logged_in? %>
            
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account<b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile",current_user %></li>
                <li><%= link_to "Settings",edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Log out",logout_path,method: "delete" %>
                </li>
              </ul>
            </li>
            <% else %>
            <li><%= link_to "Log in", login_path %></li>
            <% end %>  
          </ul>
        </nav>
      </div>
</header>
        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineExamSystem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">  
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %> 
      <%= yield %>
    </div>
  </body>
</html>